name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  RAMA_DESTINO: 'release1'
jobs:
  job1:
    permissions: write-all
    name: crea_rama
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Generate random number
      id: random
      run: echo "::set-output name=value::$(echo $RANDOM)"
      shell: bash
    - name: Example how to use the output
      run: echo "${{ steps.random.outputs.value }}"
      shell: bash
    - name: create branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with:
        # The branch to create
        branch: post-${{ steps.random.outputs.value }}
    - name: download file
      run: wget ${{ github.event.issue.body }} -O source/_posts/
    - name: commit and push new file
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "New post"
        git push -u origin post-${{ steps.random.outputs.value }}
      shell: bash
    - name: create pull request towards the main branch
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        token: ${{ inputs.secret }}
        commit-message: Auto Pull Request
        title: New post pr
        body: Auto-created Pull Request
        branch: post-${{ steps.random.outputs.value }}
        base: master
                  

  job2:
    permissions: write-all
    name: Integrar-Develop-release
    if: ${{ contains(github.event.head_commit.message, 'MERGE_RELEASE') }}
    runs-on: ubuntu-latest
    steps:
    - name: hace merge de develop a la release
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: ${{ env.RAMA_DESTINO }}
    - name: hace cambio de rama
      uses: actions/checkout@v3
      with:
        ref: ${{ env.RAMA_DESTINO }}
  job3:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests

