name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  RAMA_DESTINO: 'release1'
jobs:
  job1:
    permissions: write-all
    name: crea_rama
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install necessary Python packages
      run: pip install pandas jupyter lxml playwright beautifulsoup4 requests
    - name: Run the scraping script
      run: python scraper.py
    - name: Commit and push if content changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

  job2:
    permissions: write-all
    name: Integrar-Develop-release
    if: ${{ contains(github.event.head_commit.message, 'MERGE_RELEASE') }}
    runs-on: ubuntu-latest
    steps:
    - name: hace merge de develop a la release
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: ${{ env.RAMA_DESTINO }}
    - name: hace cambio de rama
      uses: actions/checkout@v3
      with:
        ref: ${{ env.RAMA_DESTINO }}
  job3:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests

